services:
  frontend:
    build:
      dockerfile: Dockerfile
    container_name: randomi-front
    ports:
      - "5173:5173"
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
