services:
#listes des conteneurs du docker compose
  db:
    build:
      context: ./backend
      dockerfile: Dockerfile-db
    container_name: randomi-db
    ports:
      - '5432:5432'
      #a gauche nom de l'os, à droite docker (cf docker engine et systeme de namespace)
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    
    volumes:
      - randomi_db_data:/var/lib/postgresql/data
    
    networks:
      - randomi-backend
  
  backend:
    build:
      context: ./backend
      additional_contexts:
        # this context is used to point to the parent assets folder
        assets: .
    container_name: randomi-backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}
      BACKEND_SECRET_KEY: ${BACKEND_SECRET_KEY}
    
    networks:
      - randomi-backend
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      additional_contexts:
        # this context is used to point to the parent assets folder
        assets: .
    container_name: randomi-frontend
    ports:
      - "5173:5173"
    env_file: .env
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    
    depends_on:
      - backend


networks:
  randomi-backend:

volumes:
  randomi_db_data:
