services:
  db:
    image: postgres:17
    container_name: randomi-db
    ports:
      - '5432:5432'
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    
    volumes:
      - randomi_db_data:/var/lib/postgresql/data
    
    networks:
      - randomi-backend
  
  api:
    build: ./backend
    container_name: randomi-api
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}
      - BACKEND_SECRET_KEY={BACKEND_SECRET_KEY}
    
    networks:
      - randomi-backend
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    container_name: randomi-front
    ports:
      - "5173:5173"
    env_file: .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
    depends_on:
      - api


networks:
  randomi-backend:

volumes:
  randomi_db_data:
