services:
  db:
    build:
      context: ./backend
      dockerfile: Dockerfile-db
    container_name: randomi-db
    ports:
      - '5432:5432'
    env_file: .env
    restart: always
    
    volumes:
      - randomi_db_data:/var/lib/postgresql/data
    
    networks:
      - randomi-backend
  
  backend:
    build:
      context: ./backend
    container_name: randomi-backend
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}
    
    volumes:
      - ./data:/usr/src/backend/data
    
    networks:
      - randomi-backend
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
    container_name: randomi-frontend
    ports:
      - "5173:5173"
    env_file: .env
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    
    depends_on:
      - backend


networks:
  randomi-backend:

volumes:
  randomi_db_data:
