M	assets/cards.json
A	assets/cards_backup.json
A	assets/cards_fixed.json
M	backend/src/server/game/cards/card.rs
M	backend/src/server/game/cards/exchange_card.rs
M	backend/src/server/game/cards/multi_action_card.rs
M	backend/src/server/game/cards/players_rolls_dice_card.rs
M	backend/src/server/game/database.rs
M	backend/src/server/game/modifiers.rs
A	check_problem_cards.js
A	docs/deploiement/README.md
A	docs/deploiement/procedure-deploiement.md
A	fix_image_mapping.js
M	frontend/src/js/game/events/events.js
M	frontend/src/js/game/game.js
M	frontend/src/public/assets/randomi_recto_cards_page-0074.jpg
M	frontend/src/public/assets/randomi_recto_cards_page-0075.jpg
M	frontend/src/public/assets/randomi_recto_cards_page-0076.jpg
M	frontend/src/public/assets/randomi_recto_cards_page-0077.jpg
A	frontend/src/public/assets/randomi_recto_cards_page-temp73.jpg
A	frontend/src/public/assets/randomi_recto_cards_page-temp74.jpg
A	frontend/src/public/assets/randomi_recto_cards_page-temp75.jpg
A	frontend/src/public/assets/randomi_recto_cards_page-temp76.jpg
A	frontend/src/public/assets/randomi_recto_cards_page-temp77.jpg
