[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.2.0", features = ["mysql", "r2d2", "chrono"] }
r2d2 = "0.8.10"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
