services:
  db:
    image: mysql:8.0
    container_name: randomi-db
    ports:
      - '3307:${DATABASE_PORT}'
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
    volumes:
      - randomi_db_data:/var/lib/mysql
    
    networks:
      - randomi-backend
  
  api:
    build: .
    container_name: randomi-api
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${MYSQL_DATABASE}
    
    networks:
      - randomi-backend
    depends_on:
      - db


networks:
  randomi-backend:

volumes:
  randomi_db_data:
