name: CI

on:
  push:
    branches: [ "main", "gameserver" ]
  pull_request:
    branches: [ "main", "gameserver" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - name: Installer Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Installer les dépendances
        run: cargo fetch
      - name: Lancer les tests
        run: cargo test --all --verbose

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3
      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Installer les dépendances
        run: npm install
      - name: Lancer les tests
        run: npm run test 