name: CI Backend Rust

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Installer les dépendances système
        run: sudo apt-get update && sudo apt-get install -y libpq-dev
      - name: Installer Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Lancer les tests Rust du backend
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://testuser:testpassword@localhost:5432/testdb
          BACKEND_SECRET_KEY: test_secret
        run: cargo test --all --verbose 